title: Guzhaolin's Homepage
page-top-title: Guzhaolin
top-section-bg-text: Research. Code. Impact.
home-subtitle: CS Student at Qufu Normal University
copyright-text: '&copy; Guzhaolin 2023-2025. All Rights Reserved.'
